import {
    getInputEmail,
    getInputName,
    getInputPassword,
    getInputConfirmPassword,
    getInputRememberMe,
    getInputPhoneNumber,
    getInputGender,
    getInputChooseDay,
    getInputAddress,
    getInputStreet,
} from "./UsersInput";
import {
    getInputNameProduct,
    getInputImagesProduct,
    getInputDescProduct,
    getInputPriceProduct,
    getInputLengthProduct,
    getInputHeightProduct,
    getInputWidthProduct,
    getInputWeightProduct,
    getInputBetterCapacityProduct,
    getInputScreenProduct,
    getInputRamProduct,
    getInputRomProduct,
    getInputGpuProduct,
    getInputCpuProduct,
    getInputOsProduct,
    getInputCategoryProduct,
    getInputBrandProduct,
    getInputNewnessProduct,
    getInputStatusProduct,
    getInputQuantityProduct,
} from "./ProductsInput";
import getItem from "./Item";
import PendingStyled from "./PendingStatus";
import {
    getInputAmountDiscount,
    getInputCodeDiscount,
    getInputPercentDiscount,
    getInputRangeDateDiscount,
} from "./DiscountInput";

export {
    getInputEmail,
    getInputName,
    getInputPassword,
    getInputConfirmPassword,
    getInputRememberMe,
    getInputPhoneNumber,
    getInputGender,
    getInputChooseDay,
    getItem,
    getInputAddress,
    getInputStreet,
    getInputNameProduct,
    getInputImagesProduct,
    getInputDescProduct,
    getInputPriceProduct,
    getInputLengthProduct,
    getInputHeightProduct,
    getInputWidthProduct,
    getInputWeightProduct,
    getInputBetterCapacityProduct,
    getInputScreenProduct,
    getInputRamProduct,
    getInputRomProduct,
    getInputGpuProduct,
    getInputCpuProduct,
    getInputOsProduct,
    getInputCategoryProduct,
    getInputBrandProduct,
    getInputNewnessProduct,
    getInputStatusProduct,
    PendingStyled,
    getInputAmountDiscount,
    getInputCodeDiscount,
    getInputPercentDiscount,
    getInputRangeDateDiscount,
    getInputQuantityProduct,
};
