import {
    getInputEmail,
    getInputName,
    getInputPassword,
    getInputConfirmPassword,
    getInputRememberMe,
    getInputPhoneNumber,
    getInputGender,
    getInputChooseDay,
    getInputAddress,
    getInputStreet,
} from "./UsersInput";
import {
    getInputNameProduct,
    getInputImagesProduct,
    getInputDescProduct,
    getInputPriceProduct,
    getInputLengthProduct,
    getInputHeightProduct,
    getInputWidthProduct,
    getInputWeightProduct,
    getInputBetterCapacityProduct,
    getInputScreenProduct,
    getInputRamProduct,
    getInputRomProduct,
    getInputGpuProduct,
    getInputCpuProduct,
    getInputOsProduct,
    getInputCategoryProduct,
    getInputBrandProduct,
    getInputNewnessProduct,
    getInputStatusProduct,
} from "./ProductsInput";
import getItem from "./Item";
import PendingStyled from "./PendingStatus";

export {
    getInputEmail,
    getInputName,
    getInputPassword,
    getInputConfirmPassword,
    getInputRememberMe,
    getInputPhoneNumber,
    getInputGender,
    getInputChooseDay,
    getItem,
    getInputAddress,
    getInputStreet,
    getInputNameProduct,
    getInputImagesProduct,
    getInputDescProduct,
    getInputPriceProduct,
    getInputLengthProduct,
    getInputHeightProduct,
    getInputWidthProduct,
    getInputWeightProduct,
    getInputBetterCapacityProduct,
    getInputScreenProduct,
    getInputRamProduct,
    getInputRomProduct,
    getInputGpuProduct,
    getInputCpuProduct,
    getInputOsProduct,
    getInputCategoryProduct,
    getInputBrandProduct,
    getInputNewnessProduct,
    getInputStatusProduct,
    PendingStyled,
};
